version: 2.1
orbs:
  ruby: circleci/ruby@0.1
workflows:
  main:
    jobs:
      - build
jobs:
  build:
    executor: ruby/default
    steps:
      - checkout
      - ruby/load-cache
      - run: gem uninstall bundler && gem install bundler -v 2.0.2
      - ruby/bundle-install
      - ruby/save-cache
      - ruby/test
